In [2]:
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from torch.utils.data import Dataset, DataLoader

In [2]:
df = pd.read_csv("../Dataset/QK-video_subset_5M.csv")
df.head()

,user_id,item_id,click,follow,like,share,video_category,watching_times,gender,age
0,1,1,1,0,0,0,1,1,1,4
1,1,2,1,0,0,0,1,1,1,4
2,1,3,1,0,0,0,0,1,1,4
3,1,4,0,0,0,0,1,0,1,4
4,2,5,1,0,0,0,1,1,1,4

In [3]:
df = pd.read_csv("../Dataset/QK-article_subset_5M_preprocessed.csv")
df.head()

,user_id,item_id,gender,age,exposure_count,click_count,like_count,comment_count,read_percentage,item_score1,item_score2,category_second,category_first,item_score3,read,read_time,share,like,follow,favorite
0,4153556,7356,1,5,-0.086102,0.682128,1.622231,2.018910,1.567342,0.314715,-0.07959,102,13,-1.404993,1,0.824957,0,0,0,0
1,4153556,7357,1,5,-0.096487,-0.336747,-0.419981,-0.427371,-0.234774,-0.937996,-0.07959,184,22,0.091516,1,-0.321802,0,0,0,0
2,4153556,7358,1,5,-0.097081,-0.428472,-0.423850,-0.369255,-0.424470,0.314715,-0.07959,98,13,-1.903830,1,-0.220190,0,0,0,0
3,4153556,7359,1,5,-0.097316,-0.458371,-0.425289,-0.484889,0.650476,0.314715,-0.07959,83,11,0.590353,1,-0.307286,0,0,0,0
4,4153556,7360,1,5,-0.091966,0.073558,-0.379497,-0.346488,1.061485,0.314715,-0.07959,34,5,-1.903830,1,0.157224,0,0,0,0

In [4]:
df = pd.read_csv("../Dataset/QB-video.csv")
df.head()

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_29116\1892375028.py:1: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../Dataset/QB-video.csv")

,user_id,item_id,click,follow,like,share,video_category,watching_times,gender,age
0,3502303,1375832,0,0,0,0,1,1,0,0
1,3502303,32277,0,0,0,0,0,1,0,0
2,3502303,1425848,0,0,0,0,0,1,0,0
3,3502303,1480204,0,0,0,0,0,1,0,0
4,3502303,1406570,0,0,0,0,0,1,0,0

In [6]:
df = pd.read_csv("../Dataset/QB-article.csv")
df.head()

,user_id,item_id,click,gender,age,exposure_count,click_count,like_count,comment_count,read_percentage,item_score1,item_score2,category_second,category_first,item_score3
0,4002398,1,1.0,1,7,67018,1969,0,10,0.0,3,3.0,13002,130,7.0
1,4002398,2,1.0,1,7,235105,2305,4,6,42.0,3,3.0,10402,104,7.0
2,4002398,3,1.0,1,7,4648,133,3,0,35.0,3,3.0,12300,123,6.0
3,4002398,4,1.0,1,7,1256,89,0,0,2.0,3,3.0,11304,113,8.0
4,4002398,5,1.0,1,7,6749,430,0,0,49.0,3,3.0,11302,113,6.0

In [7]:
df = pd.read_csv("../Dataset/task_0.csv")
df.head()

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_29116\1893095877.py:1: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../Dataset/task_0.csv")

,user_id,item_id,click,follow,like,share,video_category,watching_times,gender,age
0,1,1,1,0,0,0,1,1,1,4
1,1,2,1,0,0,0,1,1,1,4
2,1,3,1,0,0,0,0,1,1,4
3,1,80936,1,0,0,0,1,1,1,4
4,1,781,1,0,0,0,1,1,1,4